### ISSUE TITLE
Hello i have a problem

### ISSUE THREAD

**Issue by qianchengshuai** [nixingyang/AdaptiveReID#1]
I use colab to train the model, but cannot load your pre-trained model .How to input the pretrained_model_file_path parameter，should be placed in that folder.Hope you can answer for me.

**Comment by nixingyang** [comment]
@qianchengshuai 
Hi,
Thanks for your interest in our work.
It does not matter where the pre-trained model is stored. Just make sure that the file is readable by the program.
You may append something like `--pretrained_model_file_path "/tmp/Market1501_ResNet50_9502037.h5"` to the command.
To avoid any confusion, it is advisable to use the absolute path rather than the relative path.
I am not familiar with Colab, but I presume that you would need to upload such h5 files to Colab.
All the best.
Xingyang

**Comment by qianchengshuai** [comment]
Thanks, I found the reason

> @qianchengshuai
> 您好，
> 感谢您对我们的工作感兴趣。
> 预训练模型的存储位置无关紧要。只需确保程序可以读取该文件即可。
> 您可以`--pretrained_model_file_path "/tmp/Market1501_ResNet50_9502037.h5"`在命令后附加类似内容。
> 为避免混淆，建议使用绝对路径而不是相对路径。
> 我不熟悉Colab，但我想您需要将此类h5文件上传到Colab。
> 祝一切顺利。
> ing阳

Thanks, I found the reason

**Comment by nixingyang** [comment]
@qianchengshuai That's good to hear. Feel free to re-open the issue if it persists.
