### ISSUE TITLE
Inference model

### ISSUE THREAD

**Issue by mdne** [nixingyang/AdaptiveReID#3]
Hi,
I'd trained the model on my own dataset and got training_model.h5 file. Then I've tried to load model using keras functional like that: 
`model = tf.keras.models.load_model('training_model.h5', custom_objects={"AdaptiveL1L2": AdaptiveL1L2})`

and got an error:

`ValueError: Layer #0 (named "resnet" in the current model) was found to correspond to layer resnet in the save file. However the new layer resnet expects 6 weights, but the saved weights have 10 elements.`

So I have several questions:
1. How to load the model for inference?
2. How to make an inference on one or more images without custom datagenerator?
3. What is the size of embeddings?

Thanks

**Comment by nixingyang** [comment]
@mdne 
Hi,
The native `load_model` function would yield such error due to the reason that the [l2_regularization_factor](https://github.com/nixingyang/AdaptiveReID/blob/c9a2ee075f5ae9c1144262a84e8a85e1a5cfe1db/regularizers/adaptation.py#L35-L37) tensors are not initiated. This issue could be addressed by calling `test_on_batch` before `load_weights` as shown [here](https://github.com/nixingyang/AdaptiveReID/blob/c9a2ee075f5ae9c1144262a84e8a85e1a5cfe1db/solution.py#L1122-L1126).
Returning to your questions:
1, Define the model using [init_model](https://github.com/nixingyang/AdaptiveReID/blob/c9a2ee075f5ae9c1144262a84e8a85e1a5cfe1db/solution.py#L161). Call `test_on_batch`, followed by `load_weights`. The aforementioned steps are the same as the [evaluation](https://github.com/nixingyang/AdaptiveReID#evaluation) procedure.
2, A minimal snippet would be `inference_model.predict_on_batch(...)`. A more detailed example can be found in the [extract_features](https://github.com/nixingyang/AdaptiveReID/blob/c9a2ee075f5ae9c1144262a84e8a85e1a5cfe1db/solution.py#L661-L681) function. Please note that [`training_model` differs from `inference_model`](https://github.com/nixingyang/AdaptiveReID/blob/c9a2ee075f5ae9c1144262a84e8a85e1a5cfe1db/solution.py#L343-L350).
3, The size of embeddings is 4096. Based on my experiences from other projects, you may shrink it to 256 or 128 using [PCA](https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization#computing-a-pca), while causing reasonable performance degradation. Happy experimenting :-)
All the best.
Xingyang

**Comment by mdne** [comment]
Thank you for the explanation.
Am I right that your method assumes definition and loading the training model and makes an inference inside by calling callback?
Is there a way to load the inference model directly from file(training_model.h5) and use it? Or maybe saving a model after training as an inference model?

**Comment by nixingyang** [comment]
1, Yes, that is how my implementation works. After initiating the models (`training_model` and `inference_model`) using `init_model`, `test_on_batch` and `load_weights` successively, you may directly compute the embeddings via `inference_model.predict_on_batch(...)`. It is not mandatory to incorporate the evaluation pipeline as a callback.
2, It is not straightforward to load the inference model directly from the weights file, due to the same reason explained in my previous post. You may write a stand-alone script for inference if that is what you need.

**Comment by ElsaLuz** [comment]
Hi!
@nixingyang I am trying to load the model on Google Colab. But I am facing issues. I am a noob and I am unable to resolve this issue.

As suggested in point 1:  I have defined the model using ```init_model```. But I am unable to call ```test_on_batch``` and ```load_weights```.  

When I tried this code snippet after init_model:
```
_ = training_model.test_on_batch(train_generator[0])
# Load weights from the pretrained model 
training_model.load_weights(pretrained_model_file_path)
```

I got this error:  
```
NameError: name 'training_model' is not defined  
```
It is obvious as first I have to call  init_model in order to get  training_model. 

But when I tried this code:
```
python3 -u solution.py --dataset_name "Market1501" --backbone_model_name "ResNet50" --pretrained_model_file_path "?.h5" --output_folder_path "evaluation_only" --evaluation_only --freeze_backbone_for_N_epochs 0 --testing_size 1.0 --evaluate_testing_every_N_epochs 1
```
 It gives me this error:
```
File "<ipython-input-7-44d28dd95e5d>", line 1
    python3 -u solution.py --dataset_name "Market1501" --backbone_model_name "ResNet50" --pretrained_model_file_path "/content/gdrive/Market1501_ResNet50_9502037.h5" --output_folder_path "evaluation_only" --evaluation_only --freeze_backbone_for_N_epochs 0 --testing_size 1.0 --evaluate_testing_every_N_epochs 1
                      ^
SyntaxError: invalid syntax
```

How do we load this model? I would be grateful for your help.
