### ISSUE TITLE
Image Size Problem

### ISSUE THREAD

**Issue by mertcannkocerr** [nixingyang/AdaptiveReID#8]
Hi,
We are using Google Efficient Det for object detection and it returns images with different size(for ex. 150x200). We have two problems.
1) After image resize process with function read_image_file, we realized that program does not compute as expected since image is corrupted(or simply resized). Is there a way to compare images with different sizes rather than resizing it? We may did some implementation issues so we are going to share code snippet.

`def image_comparison(image_pil,image_no): 
    # image_pil -> pillow object that is detected by google efficient det.

    global threshold # 0.0798
    image_temp = image_pil
    image_file_path_list = updateImageFiles() # Function that returns images in given directory
  
    # Since read_image_file reads from path we resize our image_pil here
    image_array = np.array(image_temp) # RGB
    image_array = cv2.resize(image_array, input_shape[:2][::-1])

    if evaluation_only:
        if len(image_file_path_list) == 0:
            image_pil.save("/home/mertcan/Desktop/checkPath/" + str(image_no) + ".jpg", 'JPEG')
            image_file_path_list = updateImageFiles()
            return -1;       # Nothing in directory just add given image
    

        image_content_list = [
            read_image_file(image_file_path, input_shape)
            for image_file_path in image_file_path_list
        ]
        
        image_content_list.append(image_array)
        image_content_array = preprocess_input(np.array(image_content_list))
        
        image_features = inference_model.predict(image_content_array,batch_size=batch_size)
        
        distance_matrix = test_evaluator_callback.compute_distance_matrix(
            query_image_features=[image_features[-1]], # Last image is query image
            gallery_image_features=image_features[:-1], #[image_features[i] for i in range(len(image_features)-1)],
            metric="cosine",
            use_re_ranking=use_re_ranking)
        
        min=100 # Minumim similarity ratio
        index=-1 # To return image index.

        for i in range(len(distance_matrix[0])):
            if(distance_matrix[0][i]<min):
                min , index = distance_matrix[0][i] , i

        if(min>threshold):
            image_pil.save("/home/mertcan/Desktop/checkPath/" + str(image_no) + ".jpg", 'JPEG')
            return -2
        else:
            print("Return index:", index)
            return index
`
2) We had some unexpected results even at moments when resizing wasn't too important. We want to explain this with images. 
first image -> a frame in video
second image -> image that is stored in directory
third image -> query image

![Screenshot from 2021-01-06 18-12-00](https://user-images.githubusercontent.com/62841331/103786305-57c27e00-504d-11eb-9062-fbb2957b61f1.png)

![2](https://user-images.githubusercontent.com/62841331/103786483-8cced080-504d-11eb-9917-8a7bc80c178b.jpg)

![3](https://user-images.githubusercontent.com/62841331/103786502-90625780-504d-11eb-856d-98ef3cc604e9.jpg)

Computation of distance matrix between images is: 0.09410524 ( We think that is caused by size or color differences of the images)

**Comment by nixingyang** [comment]
Hi,
Thanks for your interest in our work.
- When training those person re-identification models, we have experimented with other strategies which make the samples have the same shape during the training procedure, e.g., applying zero padding. However, using direct resizing achieves the best performance on the test set. Ideally, one should use the same preprocessing pipeline in the training and test procedures.
- Alternatively, you could modify the `inference_model` so that it accepts samples with arbitrary shapes. Note that those models are fully-convolutional. Just change the height and width to `None`, and feed the test samples one by one (i.e., the batch size is one). Please find the following code snippet that I have used in other projects. You might need to make modifications as I haven't  tested it on this model:
```python
def modify_input_shape(model, input_shape, custom_objects=None):
    if np.array_equal(model.input_shape[1:], input_shape):
        return model
    vanilla_weights = model.get_weights()
    model._layers[0]._batch_input_shape = (None, *input_shape)  # pylint: disable=protected-access
    model = model_from_json(json_string=model.to_json(),
                            custom_objects=custom_objects)
    model.set_weights(vanilla_weights)
    return model
```
- What's your concern regarding the distance between the samples provided by you? Is it too high? It's better to validate the model in a query-gallery setting, just like a standard person re-identification benchmark. This is inherently a ranking problem, and the model is not making binary decisions.

All the best.
Xingyang Ni
